name: Run Mozc Updater and build LatinIME

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  GH_AUTH_TOKEN: ${{ secrets.GH_TOKEN }} # setting GH_TOKEN for the entire workflow

jobs:
  libmozc-updater:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Run Mozc Updater
        run: |
          cd libmozc-updater
          cargo run --release
  build:
    needs: libmozc-updater

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
    
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew assembleRelease